### ISSUE TITLE
sure looks nice but it is not running

### ISSUE THREAD

**Issue by syswombat** [edouard-lopez/progress-bar.sh#10]
hello
i found your progress-bar.sh script.
copy pasted change right/permission and wished to run.

but nothing happen, but also no error

so is the something needed which is not in a default debian 10 installation?

have a nice day
vinc

**Comment by shubhamkumar-revefi** [comment]
Can you be a little bit more specific about what you did so that I can reproduce the issue and understand more clearly about what's happening?

**Comment by syswombat** [comment]
Hello Scheleon
i did copy past the content of progress-bar.sh  to my one debian 10 Linux system
in a script i wrote by myself - i call it up like

the script is like

apt update 
apt install -y munin-node
systemctl status munin-node.system
progress-bar.sh 30

to add the progressbar it gives me the time to check if there is a error

but maybe i missunderstod how to use it

**Comment by edouard-lopez** [comment]
is _progress-bar.sh_ accessible from your script? From what you wrote it should be located next to your script.

If you can share a gist with your code, that would be helpful.

**Comment by nathaneltitane** [comment]
@edouard-lopez also curious as to how it actually represents a running process by completion status... how do you integrate it to show the progress on an 'apt-get install **PACKAGE**' command for instance?

**Comment by edouard-lopez** [comment]
Closing as original poster didn't give anymore details. 

@nathaneltitane it's based on the duration you provide. Not sure it fit your needs. 
Please open a different issue if you want to discuss this
