### ISSUE TITLE
Can we make the progress bar fit screen size?

### ISSUE THREAD

**Issue by jatindhankhar** [edouard-lopez/progress-bar.sh#2]
Hey,
Nice work with the progress bar, I was wondering if we could let the progress bar fit to screen size. Right now it is occupying a pre-defined (not sure if shell specific or pre-defined) space, instead of covering up the whole screen (width wise)?

**Comment by edouard-lopez** [comment]
Hi @jatindhankhar 
Currently it's pretty stupid, the width is the same as the duration and it was enough for my need. You can easily integrate the width of the terminal but I wanted something simple and straightforward (as stated in the readme). 
Have a look at the [code it's really short](https://github.com/edouard-lopez/progress-bar.sh/blob/735eb2760b0745750d4ebe11d1451cac9ff041ab/progress-bar.sh) (**<20 lines**), try to add your behavior and submit a PR.

To get the larger of the terminal use either `$(tput cols)` in a script or `COLUMNS` variable in an interactive shell as it [isn't available in a script](http://mywiki.wooledge.org/BashFAQ/091):

    COLUMNS
      Used by the select compound command to determine the terminal width when  printing 
      selection  lists. Automatically  set if the checkwinsize option is enabled or in an 
      interactive shell upon receipt of a SIGWINCH.

For instance:

     $ echo $COLUMNS
     237

**Comment by jatindhankhar** [comment]
@edouard-lopez  Thanks for the resources . 
Will try to achieve the desired result and send in a PR by this weekend :+1:

**Comment by adriano-pinaffo** [comment]
Hello, I hope you don't mind but I just created a progress bar that fits all the columns.
Please check it out: https://github.com/adriano-pinaffo/progressbar.sh

**Comment by jatindhankhar** [comment]
@adriano-pinaffo Nice :+1:  
I couldn't achieve the desired result :sweat_smile: , but your implementation looks good. Can you make a PR on the upstream ?

**Comment by edouard-lopez** [comment]
@adriano-pinaffo nice! 

You seem to have based your work on an older version, I added some tests after finding [a bug with the percentage](https://github.com/edouard-lopez/progress-bar.sh/issues/4).

I encourage you to use functions, it makes code a lot legible, easier to maintain and test, i.e. future-proof.

I'm closing this then.

**Comment by adriano-pinaffo** [comment]
@jatindhankhar, I can help you out if it didn´t work for you. Do you mind opening an issue on [my github](https://github.com/adriano-pinaffo/progressbar.sh)?

@edouard-lopez, I don´t have an issue with the percentage, as far as I know. I noticed that in your work you were, at some point, multiplying something by 100, then dividing it by 100. I just made my own implementation for the percentage. I agree with the use of functions, it´s just that this script is simple enough to have it on the "body". But if for some reason I decide to implement more funcionalities, I would totally modify it to use functions.

**Comment by edouard-lopez** [comment]
@adriano-pinaffo the percentage was broken after a refactoring based on [`shellcheck` recommandation](https://github.com/koalaman/shellcheck/wiki/SC2017) that I didn't verify. My first test will prevent such regression in the future.
