### ISSUE TITLE
Unable to set number higher than width of SHELL size

### ISSUE THREAD

**Issue by metalcated** [edouard-lopez/progress-bar.sh#3]
When you use a number like 300 per say, the bar prints each % to a new line rather than stay on the single line as the bar should.

**Comment by edouard-lopez** [comment]
**related:** #2 

Indeed, that's due to the fact we [draw the whole bar at every step](https://github.com/edouard-lopez/progress-bar.sh/blob/master/progress-bar.sh#L7). 

Do you have any suggestion on how to render this kind of scenario? (e.g. wrap, normalize, etc.)

**Comment by edouard-lopez** [comment]
closing as no feedback for a year

**Comment by metalcated** [comment]
Hey I totally missed this. The email response got stuck in the Gmail black hole.

**Comment by metalcated** [comment]
Without trying this (I'm on my phone in a car as a passenger). 

Instead of printf " ", maybe try printf " \r" for https://github.com/edouard-lopez/progress-bar.sh/blob/master/progress-bar.sh#L7 - not sure if that would break the loop or not plus you already are performing a final printf "\r" two lines down.

**Comment by edouard-lopez** [comment]
Using `\r` go back to the beginning of the line before printing the percentage:

    | 70%▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇

Not something I want.

We probably need to use `$COLUMNS` value to adjust dynamically.

If you submit a PR, I will gladly review it.

**Comment by scheleon** [comment]
$COlumns is shell variable so it won't help, I'm a beginner and it'll be my first bug to fix . I would like to fix this issue if it is still open.
